services:

  msconfigserver:
    image: jroullet/msconfigserver:latest
    mem_limit: 700m
    ports:
      - "8888:8888"
    networks:
      - healthcare
#    secrets:
#      - git_password
#    environment:
#      GIT_PASSWORD_FILE: /run/secrets/git_password


  msdiscovery:
    image: jroullet/msdiscovery:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - bankapplication
    depends_on:
      - msconfigserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msconfigserver:8888/

  mswebapp:
    image: jroullet/mswebapp:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - bankapplication
    depends_on:
      - msconfigserver
      - msdiscovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msconfigserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msdiscovery:8761/eureka/

#secrets:
#  git_password:
#    file: ./git_password.txt

networks:
  healthcare: