server:
  port: 9000
spring:
  application:
#      name of note.properties file in config server microservice
    name: "ms-notes"
#  profiles:
#    active: "prod"
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27018/notes?authSource=admin
#      authentication-database: admin
#      username: root
#      password: 123
#      database: notes
#      port: 27018
#      host: localhost
  config:
    import: configserver:http://localhost:8888/

#-----------Actuator----------------
#Will be used into docker-compose to pass the healthcheck step, service can now be pinged
management:
  endpoints:
    web:
      exposure:
        include: "*"
# Active les informations transmises par les endpoints
  info:
    env:
      enabled: true
# Configuring Info Endpoint
info:
  app:
    name: note Microservice
    description: HealthCare note scoring Application
    version: 1.0.0

#-----------EUREKA----------------
#--------------Eureka Server----------------
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

