services:

  msconfigserver:
    image: jroullet/healthcare-ms-configserver:latest
    container_name: configserver-ms
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    secrets:
      - git_password
    environment:
      GIT_PASSWORD_FILE: /run/secrets/git_password

  msdiscovery:
    image: jroullet/healthcare-ms-discovery:latest
    container_name: discovery-ms
    ports:
      - "8761:8761"
    depends_on:
      msconfigserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
#    environment:
#      SPRING_APPLICATION_NAME: msdiscovery
#      SERVER_PORT: 8761

  mswebapp:
    image: jroullet/healthcare-ms-webapp:latest
    container_name: webapp-ms
    ports:
      - "8080:8080"
    networks:
      - healthcare
    depends_on:
      - msconfigserver
      - msdiscovery
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://msconfigserver:8888/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://msdiscovery:8761/eureka/

secrets:
  git_password:
    file: ./git_password.txt

networks:
  healthcare:
    driver: "bridge"