services:

  msconfigserver:
    image: jroullet/healthcare-ms-configserver:latest
    container_name: configserver-ms
    ports:
      - "8888:8888"
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config
    secrets:
      - git_password
    environment:
      GIT_PASSWORD_FILE: /run/secrets/git_password

  msdiscovery:
    image: jroullet/healthcare-ms-discovery:latest
    container_name: discovery-ms
    ports:
      - "8761:8761"
    depends_on:
      msconfigserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  mspatientdb:
    container_name: patientdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: patientdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  msmongodb:
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
    extends:
      file: common-config.yml
      service: microservice-mongo-config

  mswebapp:
    image: jroullet/healthcare-ms-webapp:latest
    container_name: webapp-ms
    ports:
      - "8090:8090"
    depends_on:
      mspatientdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-discovery-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mspatientdb:3306/patientdb

  mspatient:
    image: jroullet/healthcare-ms-patient:latest
    container_name: patient-ms
    ports:
      - "8070:8070"
    depends_on:
      mspatientdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-discovery-config
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mspatientdb:3306/patientdb

  msnotes:
    image: jroullet/healthcare-ms-notes:latest
    container_name: notes-ms
    ports:
      - "9000:9000"
    depends_on:
      msmongodb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-discovery-config

secrets:
  git_password:
    file: ./git_password.txt

networks:
  healthcare:
    driver: "bridge"