server:
  port: 8080
spring:
  application:
    name: ms-webapp

  #------ Imported config must be quite empty to avoid loosing time from a/r -----#
  config:
    import:
      configserver:http://localhost:8888/

#-----------EUREKA----------------
#--------------Eureka Server----------------
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/